import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Container } from "@chakra-ui/react";
import SWRProvider from "./swr-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <SWRProvider>
            <Container py={["var(--chakra-spacing-4)"]}>{children}</Container>
          </SWRProvider>
        </Provider>
      </body>
    </html>
  );
}
